# Generated by Django 5.2.7 on 2025-10-05 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('LIFE', 'Lifestyle'), ('EDU', 'Education'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel')], default='TECH', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
